name: sky_seal
description: Sky Seal

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.5
  flutter_card_swiper: ^6.0.0
  animations: ^2.0.7
  card_swiper: ^3.0.1
  animated_size_and_fade: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  indexed: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true